### ISSUE TITLE
Exercise 1

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#1]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise1

Create a class User with name and age as its attribute.Instantiate two objects user1 and user2 with some value. Create a method compare that compares the age of user1 and user2. The method should be called in this way: 
user1.compare(user2)
This method should return output like "john is older than mary" or "mary is older than john" based on their age comparison. All Exercises should be submitted by following OOPs.

**Comment by segunadeleye** [comment]
Looks good. Let's have a case for same age as well.
