### ISSUE TITLE
Exercise 10: Email and URL Format Validation

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#10]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise10

The form you create like https://www.dropbox.com/s/qccm98brx2hdbrw/Form_validation.png. Add validations for the correct format of email and homepage (url) using regular expressions. Please use only Object oriented approach to write your code.

**Comment by segunadeleye** [comment]
Similar to Exercise 6, you are to show validation error for each invalid field.

**Comment by oubaka** [comment]
Fixed the regex and made corrections as adviced

**Comment by segunadeleye** [comment]
Looks good
