### ISSUE TITLE
Exercise 11: Matching Numerical Values and Event Propogation

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#11]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise11

Create a form with two text fields labeled "Enter Number" and "Result". When I enter something in first text field and submit the form, it should write true in second text field if entered value is numeric otherwise false. Also if entered value is not numeric, form should not be submitted. Please use only Object oriented approach to write your code.

**Comment by segunadeleye** [comment]
Fix the issues as pointed out.

**Comment by oubaka** [comment]
Updated numerical check from parseInt to using isNaN
