### ISSUE TITLE
Exercise 12: Domain/Subdomain Matching

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#12]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise12

Create a simple form with a text field and a submit button. When I enter a URL in this text field and submit the form, it should alert me the domain name from the entered url. For example, If I enter:
http://example.com/folder/file.html, then on submitting the form it should alert something like:
Domain: example.com.

With subdomain: http://vinsol.example.com/folder/file.html, then on submitting the form it should alert something like:
Domain: example.com
Subdomain: vinsol.
Basic Idea is to extract domain name and subdomain from a URL.
Note: Use Regular Expressions for this exercise. Please use only Object oriented approach to write your code.

**Comment by segunadeleye** [comment]
- www.dealdey.com or blog.dealdey.com are valid URLs as well
- www.dealdey.com (with or without protocols) should only display `Domain: dealdey.com` and not `Domain: dealdey.com, Subdomain: www`
- http://www.dealdey.com/dsds (with or without protocols) should display `Domain: dealdey.com` and not `Domain: dealdey.com/dsds`
- Refer the question for the requirements for the exercise.
- The regex validation is not working properly. Validation passed for this YRL `http://dealdey.com/dsdsksd/-,`
- Finally, if there's a subdomain, the output should look like this.

```
Domain: example.com
Subdomain: vinsol
```

**Comment by oubaka** [comment]
Fixed the regex and made corrections as adviced

**Comment by segunadeleye** [comment]
All good
