### ISSUE TITLE
Exercise 3: Maximum 3 Checkbox Selected

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#3]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise3

Create a list of checkboxes (Sunday, Monday, Wednesday, Thursday, Tuesday, Friday, Saturday and None). Now when I start checking these checkboxes, it should not let me check more than 3 checkboxes. When I try to check on 4th checkbox it should alert me as "Only 3 days can be selected. You have already selected sunday, monday and tuesday". Now when I click on None, all other checkboxes should be deselected. Also when 'None' is selected and I select any other option (lets assume Sunday), that option (Sunday) will be selected and None will be deselected.

**Comment by segunadeleye** [comment]
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise3/index.js#L2
  How about selecting by id. It is the fastest selector. Or use `querySelector` which returns the first element found in the DOM.
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise3/index.js#L1
  How about using class selection.

Apart from these, everything looks good. Closing this for now, but make sure you make the specified changes.
