### ISSUE TITLE
Exercise 5: Dynamic Table - Add Rows, Edit and Delete Existing Rows

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#5]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise5

Create a table. When you click on 'Add new row' button:
It should add a new row in the table.
In the name and email column there will a text field.
In the action column there will be a button save.
When you enter some value in text fields and click save, then:
Values will be saved (if valid). i.e. Name and Email should be present, Email should be a valid email.
Text fields will be replaced by the values entered.
Save button will be replace by Edit / Delete links. You should be able to delete row by clicking on the Delete link, and edit value by clicking on the Edit link.

**Comment by segunadeleye** [comment]
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise5/index.html#L33
  https://github.com/oubaka/javascript_tutorial/blob/master/exercise5/index.html#L47
  Don't use HTML event attribute. Use `addEventListener()`. Avoid tight-coupling your HTML and Javascript.
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise5/controller.js#L88-L90 and https://github.com/oubaka/javascript_tutorial/blob/master/exercise5/controller.js#L93-L95
  These two blocks of code can move into a method.
- You app should tell me which field is invalid. For example, there should be an empty field error notification for Name and Email fields, and a separate validation for correct Email format.
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise5/controller.js#L103-L107
  This can be refactored to just 2 lines of code.
- Use the `doc = document` approach where necessary.

**Comment by oubaka** [comment]
Refactored the code and made corrections as adviced

**Comment by segunadeleye** [comment]
- These can still be handled by a method.
  https://github.com/oubaka/javascript_tutorial/blob/master/exercise5/controller.js#L102
  https://github.com/oubaka/javascript_tutorial/blob/master/exercise5/controller.js#L105

**Comment by oubaka** [comment]
Refactored the methods as adviced

**Comment by segunadeleye** [comment]
All good now. :100: :+1:
