### ISSUE TITLE
Exercise 6: ( Form Validation Using JS)

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#6]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise6

Create a form like https://www.dropbox.com/s/qccm98brx2hdbrw/Form_validation.png and add JS validations to that form. When you click on 'Go' JS will check all text fields, and give an alert like "Login Id can't be empty". One alert per empty field. For textarea it should check for empty and min length of 50 characters. If any field is invalid then it should not submit the form. Also It should also confirm "Receive Notification"

**Comment by segunadeleye** [comment]
You are to show one alert for each empty field.

**Comment by oubaka** [comment]
Fixed alerts as adviced

**Comment by segunadeleye** [comment]
Good!
