### ISSUE TITLE
Exercise 7: Name Input in Alert and Welcome in Page Content

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#7]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise7

Create an HTML page, when it opens in Browser, it should prompt twice. Once for first name and second for last name. When you enter first and last name, it should alert you as "Hello firstname lastname." After alert, it should put that text in html page.
Note: Keep in mind when you take inputs from users, always consider cases where user has entered null or blank values (few white spaces). User may press ESC button. In such cases you should not accept the input.

**Comment by segunadeleye** [comment]
Good!
