### ISSUE TITLE
Exercise 9: Move countries from one box to the other

### ISSUE THREAD

**Issue by oubaka** [oubaka/javascript_tutorial#9]
https://github.com/oubaka/javascript_tutorial/tree/master/exercise9

Create two multiple selection box. First box contains list of countries and when you select a country and click on Add button, selected country will disappear from first box and appear in second box. When you select a country from second box and click on remove button it will disappear from second box and appear in first box

**Comment by segunadeleye** [comment]
The `add()` and `remove()` methods can be just one method.

**Comment by oubaka** [comment]
Used one method as adviced

**Comment by segunadeleye** [comment]
Looks good. Just some observations.
- Don't couple your view with javascript. Always have all your event handlers in your javascript files.
- https://github.com/oubaka/javascript_tutorial/blob/master/exercise9/controller.js#L28
  Is this check needed?
- An alternative to passing true or false as argument is that you can have a method that takes the source and the destination elements as arguments. This way, there will be no need to do the `isSource` check.
